### ISSUE TITLE
tapiro can't return non-200 status codes, except for 4xx

### ISSUE THREAD

**Issue by giuscri** [buildo/retro#183]
tapiro should at least provide the possibility of returning 5xx status codes

/cc @calippo

**Comment by calippo** [comment]
This can be done using `statusCodes` fn as used here https://github.com/buildo/retro/blob/505e639f8b39c95f54212de44fae08f5c5bf2362/tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala#L143

Here you have an example:
```scala
object ControllerEndpoints {

  def create[AuthToken](
      statusCodes: String => StatusCode = _ => StatusCode.UnprocessableEntity
  )(
      implicit codec0: JsonCodec[SpittyCash],
      codec1: JsonCodec[Errore.Errorone],
      codec2: JsonCodec[Errore.Errorino],
      codec3: PlainCodec[String]
  ) = new ControllerEndpoints[AuthToken] {
    override val ghetto: Endpoint[String, Errore, SpittyCash, Nothing] =
      endpoint.get
        .in("ghetto")
        .in(query[String]("at"))
        .errorOut(
          oneOf[Errore](
            statusMapping(statusCodes("Errorone"), jsonBody[Errore.Errorone]),
            statusMapping(statusCodes("Errorino"), jsonBody[Errore.Errorino])
          )
        )
        .out(jsonBody[SpittyCash])
  }
}
```

Improving the way this is done is part of https://github.com/buildo/retro/issues/68

**Comment by giuscri** [comment]
This means I have to create error types like `CreateCampingError`, is that correct?https://github.com/buildo/retro/blob/505e639f8b39c95f54212de44fae08f5c5bf2362/metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ModelSuite.scala#L144-L174

**Comment by calippo** [comment]
Correct, in the previous example the controller would be 

```scala
sealed trait Errore
object Errore {
  case class Errorone(message: String) extends Errore
  case class Errorino(message: String) extends Errore
}

case class Male(name: String)

trait Controller[F[_], AuthToken] {
  @query
  def ghetto(at: String): F[Either[Errore, SpittyCash]]
}

```

**Comment by calippo** [comment]
@giuscri waiting your ack to close this, linking it however in https://github.com/buildo/retro/issues/68
