### ISSUE TITLE
Fix @path in tapiro

### ISSUE THREAD

**Issue by calippo** [buildo/retro#185]
`@path` annotation is currently broken in tapiro. However, this is pretty useful in general. 

Currently, metarpheus doesn't provide both `@path` and `controllerName`. Tapir requires both data.

**Comment by calippo** [comment]
@gabro 

```scala
```

**Comment by gabro** [comment]
Immagino ti riferisci a `ctrl`?

**Comment by calippo** [comment]
sì

**Comment by calippo** [comment]
Qual'era lo scopo di `ctrl` e `name`? ha semanticamente senso usare uno di quelli?

**Comment by gabro** [comment]
Facciamo una call veloce che mi spieghi cosa stai facendo?

**Comment by calippo** [comment]
- remove `ctrl`
- remove `body`
- add `controllerType`

**Comment by calippo** [comment]
@gabro what name would you give to tapiro's autogenerated class/traits? path or controller nmae?

I think using path name is more natural:

```scala
@path("user")
UserController {
  @query
  def findUser...
}
```

```scala
val userController = new UserControllerImpl[IO, String]()
val routes = UserHttp4sEndpoints.routes(userController) //as opposed to UserControllerHttp4sEndpoints
```

However, it means tapiro have to extract the name from a route segment. This looks a little clunky, it might be nicer to have both `controllerType` and optional `pathName` in `Route` definition.

**Comment by gabro** [comment]
I agree pathName (optional) makes sense.
For the name, what about `UserHttpRoutes.create`?

**Comment by calippo** [comment]
We have both `Http4s` and `AkkaHttp` routes, that's why they have different names. Currently, they cannot be used together, we can probably just use `Http`.

**Comment by calippo** [comment]
Names will behave as follow:

##  Tapir Endpoints
- Computed: concatenation of `pathName` (Uppercase first letter) and `TapirEndpoints`
- Named: `tapirEndpointsName`

This is also used as name of tapir endpoints file.

## Http Endpoints
- Computed: concatenation of `pathName` (Uppercase first letter) and `HttpEndpoints`
- Named: `httpEndpointsName`

This is also used as name of http endpoints file.

## Path Name
Just used for the route.

## Controller Name
Proper controller type.
