### ISSUE TITLE
Wrap POST body as in wiro

### ISSUE THREAD

**Issue by gabro** [buildo/retro#203]
In order to preserve the same semantics as wiro, we want to allow multiple parameters in `@command` such that

```scala
@command
def aCommand(a: String, b: Int)
```

will accept the following json body

```json
{ "a": "hello", "b": 42 }
```

In order to do this we need to:
- wrap everything into a generated case class in the tapir endpoints
- unwrap the case class when using `toRoutes` in Http4s (and probabily in similar way for Akka Http)

**Comment by tpetrucciani** [comment]
I can work on this, if you're not already planning to.

I suppose we want the wrapping for all commands, including those with a single parameter? (for simplicity and for compatibility with wiro)

we'll probably have to generate JSON codecs for the generated case classes too: I suppose we can add imports for Circe in the generated code and generate the declarations for Circe (semiauto?) codec derivation together with the classes
