### ISSUE TITLE
Tapiro CI fails because of missing curl

### ISSUE THREAD

**Issue by tpetrucciani** [buildo/retro#208]
Tapiro CI currently fails on `waitIsUp` because it can't run `curl`:
```
[info] [error] java.io.IOException: Cannot run program "curl": error=2, No such file or directory
```

The test runs successfully on my computer.

I suppose it's because `scala-sbt-alpine` doesn't have `curl` (it only installs it temporarily to install `SBT`).

**Comment by tpetrucciani** [comment]
@gabro for ☝️– assuming I understood the problem – would it make sense to replace the current `run` of `tapiro/ci/test.yml` to instead run a script `test.sh` like this?
```
#! /bin/sh

set -e

apk add --no-cache curl
sbt -batch ';tapiroCore/compile ;sbt-tapiro/scripted'
```

(or just inline it in `test.yml` maybe)

**Comment by gabro** [comment]
That’s perfect, nice catch. I can review the PR if you send it
