### ISSUE TITLE
[fragmented-doc] Fragmented documentation

### ISSUE THREAD

**Issue by bennesp** [buildo/retro#296]
I noticed that in this repo `enumero` doesn't have any README, in contrast to, for example, `tapiro`.

Both have documentation on a [separate site](https://buildo.github.io/retro/docs/enumero/introduction), but that is quite inconsistent.

We really should use the same methodology for the documentation, and it would be good to have a single source of truth. Maybe we could always use the separate site, and create a README per project, linking its documentation

## sub-issues

- [x] Missing doc in https://buildo.github.io/retro/docs/mailo #297 
- [x] Update Tapiro doc at [https://buildo.github.io/retro/docs/tapiro](https://buildo.github.io/retro/docs/tapiro) #298 **[bennesp]**

**Comment by gabro** [comment]
Most repos were once separate, but we then merged them into this monorepo.

The idea is to use https://buildo.github.io/retro/ as the documentation website, and the READMEs should only point towards that website (in the respective section, see the navbar on top)

Does that answer the question?

**Comment by bennesp** [comment]
> The idea is to use https://buildo.github.io/retro/ as the documentation website, and the READMEs should only point towards that website (in the respective section, see the navbar on top)

If I get it right, and if this is the idea, we should then:
- Add READMEs to subproject, if missing (example: `enumero`, `toctoc`, `sbt-buildo`)
- Only point towards that website in the README (in contrast to what is done for example in `mailo`, `tapiro`)

**Comment by gabro** [comment]
Yep. I'm actually also fine in not having READMEs at all, to be honest, but if the project has them, they should point to the website.

**Comment by bennesp** [comment]
I know I am a [precisino](https://dictionary.cambridge.org/dictionary/italian-english/precisino), but since some READMEs are present, do you prefer to remove them at all or to add some READMEs to the other projects?

I love consistency. If there is something I hate more than using tabs instead of spaces is using both tabs **and** spaces inside a project 😄

**Comment by gabro** [comment]
Hehe, I like consistency too. I would remove them all (but make sure that the information is preserved on the website, otherwise let's open an issue for moving the content from the readme to the website) except for the main readme

**Comment by bennesp** [comment]
I opened 2 sub-issues, please double-check that I covered all the projects, I could have missed someone due to low knowledge of this repository and buildo projects
