### ISSUE TITLE
[fragmented-doc] Missing doc in https://buildo.github.io/retro/docs/mailo

### ISSUE THREAD

**Issue by bennesp** [buildo/retro#297]
← #296

## requirements
Mailo documentation should be moved from its [README](https://github.com/buildo/retro/blob/master/mailo/README.md) to the [website of retro documentation](https://buildo.github.io/retro/docs/mailo)

**Comment by gabro** [comment]
Duplicated of this https://github.com/buildo/retro/issues/43. I'll keep this one
