### ISSUE TITLE
[fragmented-doc] Update Tapiro doc at https://buildo.github.io/retro/docs/tapiro

### ISSUE THREAD

**Issue by bennesp** [buildo/retro#298]
← #296

## requirements
Tapiro documentation is present in a different fashion in its [README](https://github.com/buildo/retro/blob/master/tapiro/README.md) and on the doc [website](https://buildo.github.io/retro/docs/tapiro/introduction)

They should be merged and, afterward, the README should be deleted

**Comment by gabro** [comment]
Ok, tapiro docs in the readme are just obsolete and can be removed without problems.
