### ISSUE TITLE
Polish usage of PrintWriter

### ISSUE THREAD

**Issue by gabro** [buildo/retro#42]
## description
See comments here: https://github.com/buildo/metarpheus/pull/61#discussion_r131359393

**Comment by tpetrucciani** [comment]
Closing this because we're not using `PrintWriter` any more – we're not printing anything – so there's nothing to do (unless I'm misunderstanding? cc @gabro)

**Comment by gabro** [comment]
👍 looks right, I removed the CLI bit.
