### ISSUE TITLE
Fix parametric types and json codecs names

### ISSUE THREAD

**Issue by calippo** [buildo/retro#74]
![image](https://user-images.githubusercontent.com/2476080/64016747-11d7da80-cb28-11e9-86e8-f29d9fd63f1c.png)

**Comment by tpetrucciani** [comment]
Questo l'avevo guardato un po' venerdì.

Non ho lo stesso output della screenshot (immagino per cambiamenti successivi) ma direi che è sempre sbagliato:
```scala
      botSummary: JsonCodec[BotSummary],
      id: JsonCodec[Id],
      unit: JsonCodec[Unit],
```

Ho `JsonCodec[Id]` che non ha senso invece di `JsonCodec[Id[Bot]]`. Lo stavo cambiando invece facendo la conversione da tipi di metarpheus a tipi di scalameta, non ho finito di provarlo in tutti i punti ma sembrava ridare `Id[Bot]` giusto.
